### ISSUE TITLE
Refactor: Robust check for required/not required for minor shopping

### ISSUE THREAD

**Issue by SadieDragon** [SadieDragon/TPR-Hints-Tool#103]
### Overview
Figure out a better way to distinguish the required. There's currently a bug with (not required) not being listed.

### Tasks to Complete
*Really, this is just further information as a checklist*
- [ ] Spoiler log tab options
  - [ ] Heart Pieces / Heart Containers to be auto-marked
  - [ ] Auto Mark Jovani by default (if this is off, then mark the above off too)
- [ ] Scan the spoiler log spheres for (Jovani)
  - [ ] If heart stuffs is marked as not auto-marked, override

**Comment by SadieDragon** [comment]
Jovani has been ripped out and pushed down the road to 1.0

**Comment by SadieDragon** [comment]
What actually happened is that the text determining the usefulness of a check was changed, again, again, and I haven't fully figured it out.

I will be setting up a copy of the web gen to generate a TON of seeds and have the ability to find different examples of the different cases without plandomizing it.
