### ISSUE TITLE
Feature Request: Allow Agitha to show "bad" items as well

### ISSUE THREAD

**Issue by SadieDragon** [SadieDragon/TPR-Hints-Tool#23]
### Overview
While passing this around to my close not-tpr friends, it was suggested that I also make Agitha display bad items. At first glance, I thought this cheaty, but realized it was only going to be poe souls and heart (items), and thus decided to let it pass.

### Tasks to Complete
- [ ] Scan the spoiler log's checks for all of the Agitha checks (thankfully they're the first 24 checks)
- [ ] Heart Stuffs
  - [ ] Scan her checks for heart containers and heart pieces, storing the bugs with those items
  - [ ] Create a button to click to reveal them
  - [ ] Figure out how I wish to display them
- [ ] Poe Stuffs
  - [ ] I would like to remove this if Jovani is excluded and/or has nothing
  - [ ] Scan her checks for poe souls
  - [ ] Create a button to display them
  - [ ] Figure out how I want to display them

### Further Information
Agitha is the first 24 checks of the spoiler log, given it goes alphabetically- but keep in mind that Female is grouped together and Male is in another group.
I am not sure how I want to accomplish the display; I've already mentioned that I do feel like pop-ups are a bad idea.

### OG Text:
I am going to lock this behind a button- I do not want this to be visible from the get-go because this can reveal something that's not required that makes an area barren (aka, super powerful and super cheaty to some.)

I see the reason this is wanted, I see a reason why it's not. This will be an option, and I want to add it to post-completing agitha.

**Comment by SadieDragon** [comment]
Reminder to self; poe souls *might* be a moot point. For everything but no-logic. so maybe have a poe souls button
