### ISSUE TITLE
To-Do: Save Option

### ISSUE THREAD

**Issue by SadieDragon** [SadieDragon/TPR-Hints-Tool#28]
### Overview
This is a priority option that has been haunting me since day 1. The issue is not that getting the information from the widget itself is hard, but that the widgets are now spread across multiple files, and affected in multiple places.

### Tasks to Complete
- [x] Finish resolving ( #78 ), as it will make this so much easier to do
- [x] Create the button on the main page
  - [ ] Add an option for the user to delete current saves
  - [ ] Add an option for the user to overwrite the current save, instead of creating a new one
  - [ ] Add an option for the user to pick an output location, but default to the seed name
- [x] Obtain all of the information from the different widgets
  - [x] Figure out how to do this in a flexible manner, as widgets will be added over time.
- [ ] Store to the designated file

### Further Information:
- ``ScrolledText`` widgets store as a frame, with a scrollbar and a textbox. The textbox has the information, use ``.get('1.0', tkinter.END)`` to get the information.
- All of the current checklists use a var that stores their state. Not sure if this could be used.
- Dropdowns will do the same, in the future.

### OG Text:
Does what it says on the tin.

I have no thoughts currently but I want this issue open so I remember to come back to it.

**Comment by SadieDragon** [comment]
Figuring out how to pull the information from multiple files into 1 constant variable in one will make life easier. #76

**Comment by SadieDragon** [comment]
#78 is the actual issue that will make this so much easier.

**Comment by SadieDragon** [comment]
Breaking out the user choice into a new issue.
