### ISSUE TITLE
Enhancement: Random text for the shopping tab texts

### ISSUE THREAD

**Issue by SadieDragon** [SadieDragon/TPR-Hints-Tool#29]
### Overview
A funny nicety, more than a need, change the text that says what the checklist is about, based on the amount of rewards a person gives you. (This does not apply to COO, which will have a static "The following can be found here" or "This has nothing for you")

### Tasks to Complete
- [ ] Agitha
  - [ ] Determine the different texts for good
  - [ ] Figure out how many good she has, and apply appropriate text based on ratio
- [ ] Jovani
  - [ ] Figure out the different texts for 1 good item vs 2 good items
  - [ ] Figure out which he meets, and apply appropriate text.

### Further Information
Checks can be excluded, which will affect the ratio. They should not be hard coded, and I need to figure out how to find the denominator of the ratio.

### OG Text:
Agitha: "She is willing to share [] happiness with you!" ([] based on how many items (later on?))
Jovani: "He has learned from his ways, and is willing to reward you:" (maybe adjustable text definitely later on)

This was supposed to be added, I forgot about it, this was requested for some consistency with the completed page.
