### ISSUE TITLE
Possible Cross-Platform Incompatibility: Tkinter is sometimes not standard

### ISSUE THREAD

**Issue by SadieDragon** [SadieDragon/TPR-Hints-Tool#3]
### Overview
The unix (posix) children sometimes decide that Tkinter is not a default lib that it needs to install. This creates the obvious issue that this tool is built on Tkinter, but some people on a unix (posix) system may not be aware of this, which is an end-user hazard.

### Tasks to Complete
- [ ] Verify that the README conveys this, as clearly as possible, as a temporary fix.
  - [ ] Figure out the unix systems that do not default install.
  - [ ] Figure out the best solution(s) for that.
  - [ ] Update README to convey this learned information.
- [ ] Make sure the packager accounts for this in some manner. (Further to-do is not available at this time.)

### Further Information
Unix/Posix includes: ChromeOS (apparently), MacOS, Debian, Ubuntu, Arch, (other linuxes)
Look at the comments below for current gathered information. [I will update this later to consolidate this information.]

### OG TEXT:
I can fix this. And if I distribute this, I need to fix it, because *mac is posix.*

**Comment by SadieDragon** [comment]
As much love as this has garnered, this is completely overwritten by the current work implementing a new library that needs installed anyway. Cross compatibility not a problem anymore.
