### ISSUE TITLE
Feature: Hint "Journal"

### ISSUE THREAD

**Issue by SadieDragon** [SadieDragon/TPR-Hints-Tool#33]
### Overview
~~Figure out how to handle the not special sign hints. (The signs which say "they sat that x is y"). The main issue here is that I do not want to autofill them out the gate, nor will I be willing to give an option such as that, but I could see the desire for checking what hints you already have found.~~
Present all not-special hints in a tab where you can hide the information and reveal it.

### Tasks to Complete:
- [ ] Pull the hints out from the normal parsing loop
- [ ] Remove the indicator text ('They say that') from the text
- [ ] Save the majority of the hints somewhere
- [ ] Add COO's special hint on the last line to the list ( #43 ) and ( #54 )
- [ ] Figure out how to display
  - [ ] Progressive reveal?

### Further Information
Some of this is mentioned, but
- COO has an extra line, with a hint.
- All dungeon signs have an extra hint at the end for most hint strengths
- Weak makes this more difficult
- Junk hints could be determined very easy by "do they say that?"
- For everything but no logic, {reward} (item)

### OG Text:
Putting this here for me to ramble about later. I don't have thoughts rn.
