### ISSUE TITLE
To-Do: Dungeon Signs

### ISSUE THREAD

**Issue by SadieDragon** [SadieDragon/TPR-Hints-Tool#34]
### Overview
The original text actually makes this pretty clear: Dungeon signs display where the big key is on most hint strengths, and also an extra hint. Maybe have an option to autofill the big keys like a shopping list?

### Tasks to Complete
- [ ] Pull out the dungeon signs from the rest
- [ ] Put the normal hint back into the majority pool
- [ ] Parse the big key hint
- [ ] Figure out how to display

### Further information
Temple of Time (ToT) has 2 signs, one of which does not actually have the big key hint.
Goron Mines (GM) has 1 sign, but the key is split into 3 shards, and thus has 3 lines.
Perhaps consider importance marking from the user?

### OG Text:
These *are* formatted differently and i've realized that this should be its own tab.

The different hint strengths affect these. Need research.

Maybe have the dungeon tab overarching, then sub notebook widget with the tabs on the side instead?

ToT has 2 signs.... do any other dungeons? Not that i can think of. (why is tot special, again?)
GM has a sign with 3 different key shards listed.

This will later be a project.

Part of init release to get the default down.
