### ISSUE TITLE
Major Refactor: Restructure the Shopping List tabs

### ISSUE THREAD

**Issue by SadieDragon** [SadieDragon/TPR-Hints-Tool#54]
### Overview
Jovani needn't be his own tab, nor does COO (or once the fishing hole). Agitha, however, can stay a major shopping list tab as she will be frequently visited

### Tasks to Complete
- [ ] Redesign Jovani's tab into the Minor Shopping tab
- [ ] Figure out how to write the Minor Shopping class
- [ ] Figure out how I want to design the tab for Jovani and COO

### Further Information
See the OG text, and comments, for more information; I will fill this out later.

### OG Text:
OG Title: (With the new file structure, maybe it'll be easier to make the shopping list tab with sub tabs and shortcuts?)

Or even keep Agitha a major shopping tab with her own tab, and have a minor tab for things you'll come back to later but don't need to quickly nav to often.

Shopping Tabs
  -> Major Shopping Tab
      -> Agitha's Shopping Tab
  -> Minor Shopping Tab
      -> Jovani's Shopping Tab
      -> COO ( #43 )
      -> Fishing Hole ( #31 )
      -> Much simpler Dungeon tab (BKs) ( #34 ) (I can see this being major)

**Comment by SadieDragon** [comment]
So. Here's a thing to think about. Let's look at the 3 big targets.

- Jovani: ``"20 souls reward: {Trap} (not required)  60 souls reward: {Trap} (not required)"``
- COO: 
  - "They say that the reward for {Cave of Ordeals Floor 17 Poe} is an {orange Rupee} (not required)."
  - "They say that the reward for {Cave of Ordeals Floor 33 Poe} is a {trap} (not required)."
  - "They say that the reward for {Cave of Ordeals Floor 44 Poe} is a {Temple of Time small key} (not required)."
  - "They say that the reward for {Cave of Ordeals Great Fairy Reward} is a {trap} (not required)."
  - "They say that {Zora's Domain} is on the way of the hero."
- Fishing Hole: ... *Oh wait a minute.*

2 key takeaways here out the gate:
- COO is a list of text, not just a one-liner (why is jovani not like this? but ok)
- ***Fishing hole does not actually have a hint sign.*** Woopsies. I mean, I could make it work, but I am removing that from the pool. (Lemme go do that real quick)

**Comment by SadieDragon** [comment]
Anyway, now that I am done with yak shaving, again, for now.

*I say, having ideas for restructuring the issues completely brewing*
- COO has an extra hint, which needs to be shoved back into the normal-hints queue *somehow*; maybe store them into a file for ease?
- {reward} (quality) is a recurring theme ***but*** I cannot rely on the (quality) ( #71 )
- Hey, look at that. {Floor}. I should probably write a function which yoinks the data from the {}s and strips them of their {}s, hm?
