### ISSUE TITLE
New Feature: Alternative default look for shopping lists

### ISSUE THREAD

**Issue by SadieDragon** [SadieDragon/TPR-Hints-Tool#64]
### Overview
Create an optional default for the shopping lists, and really even the default (with focus on shopping), to use dropdowns instead of typing it out.

### Tasks to Complete
- [ ] Get a list of all items that each could have
- [ ] Figure out how to make it expandable more easily
- [ ] Flesh out the to-do list when it becomes a main focus

### Further Information
For glitchless:
- COO and Jovani cannot have Shadow Crystal 
- COO can never have clawshot or spinner
- COO Floor 33 and 44 can never be ball and chain or dominion rod
- COO Floor 44 and GF can never be double claw.

### OG Text:
Create a dropdown list of items that can be obtained from the person / place.

Leave an option for "I would like a notebook" vs "I would like dropdowns".

Notes:
- Fishing hole bottle can only be the coral earring
- COO and Jovani cannot have Shadow Crystal (ever)
- COO can never be clawshot or spinner, at all
- COO Floor 33 and 44 can never be b&c or ddr
- COO Floor 44 and GF can never be double claw. (It also can't be the first sword but that does not matter.)

**Comment by SadieDragon** [comment]
For future reference;

Please understand that "COO" is all 1 tab, with 4 different checks *17, 33, 44, GF*.
