### ISSUE TITLE
To-Do: Create Options and Preferences

### ISSUE THREAD

**Issue by SadieDragon** [SadieDragon/TPR-Hints-Tool#9]
### Overview
This is a collection hub of possible options, some of which have not yet been converted to issues of their own. While this is a bad practice, I do not want to clutter the issues page with stale issues that will not be resolved for another month or so, and I want a hub for people to see what is already planned.

### Tasks to Complete
- [ ] Save all the data on the tracker 
  - [x] Saving Pt 1 ( #28 )
  - [ ] Reloading
  - [ ] Saving Pt 2 ( #112 )
- [ ] UI changes
  - [ ] Selection for dark mode, light mode, system default
  - [ ] Selection for the different color palettes that come from default
  - [ ] Background Color in general, for streamers
  - [ ] Font ( #56 )
  - [ ] Font Size ( #69 )
- [ ] Autofill race mode with headers? ( #106 )

### Further Information
A race mode has already been created, and implemented, but is very basic.

### OG Text:
Would also need to figure out how to more cleanly save preferences.

Considered options:
- Manual option: Do things yourself instead of having the program do it for you
- Save the notebook: Save your progress (this will be an issue of its own when i get around to doing this because yeah this feels super important). Pretty straightforward.
- Background colors for streamers/recorders?

Thoughts and discussion are welcome. A discussion will be opened for this to not clutter this issue.

**Comment by SadieDragon** [comment]
While bits of this are being implemented, I'm setting the hard deadline for the default options to be out by the end of the graphics update

**Comment by SadieDragon** [comment]
Added the preferences to the list
