### ISSUE TITLE
Major Refactor: Use other options to make a scrollable checklist

### ISSUE THREAD

**Issue by SadieDragon** [SadieDragon/TPR-Hints-Tool#91]
### Overview
When originally choosing a solution, I found only ``ScrolledText``. This has caused some headache, and some trouble, and has really felt hacky. @Ecconia also made it even more apparent how illogical that felt, and so in trying to show him the reason why- same words- different results. Pick one of these and implement it.

### Tasks to Complete
- [x] Pick an implementation (see Further Information)
  - Customtkinter won.
- [x] Do I need to update readme? Checks (is there an extra package which needs installed?)
  - [x] Yes: The user will now also need to ``pip install customtkinter``.
  - [x] They will also need to ``pip install CTkMessagebox`` *sad noises that it's an extension but still preferrable*
- [ ] Refactor and Restructure - *More complete changelog in the discord*
- [ ] Bug squish!

### Further Information
- Canvas (https://stackoverflow.com/questions/62519796/very-long-checklist-box-with-tkinter)
- CtkScrollableFrame (https://customtkinter.tomschimansky.com/documentation/widgets/scrollableframe/)
  - needs a pip install (``pip install customtkinter``)
- ...

**Comment by SadieDragon** [comment]
CTK ***does*** need an end user install. It will *also* require a complete refactor of the code to use primarily it.
Yay! Relearning from scratch!

Going to prep new version.

**Comment by SadieDragon** [comment]
_**This will be updated with changes that I make.**_ - I do not feel like messing with markdown formatting when I'm in a groove.

- Convert the root window to a new python file (based off of Ecconia's work https://github.com/SadieDragon/TPR-Hints-Tool/blob/ecc-wrecks-havoc/hints/ProgramInstance.py), as it is good practice
- Update the notepad window to the new format (EEEEEEEE it's so nice)
- Add error handling, like I should have from the start. If i think of a possible error that I can catch, I can add it to the error handling file.
  - Forgetting to add an options to command handling
- Update the "main_page" to be now "options_tab", as that is really what it is.
  - Borrowing a lot of work from Ecconia here, but also updating some functions to be more flexible for the future.

**Comment by SadieDragon** [comment]
It is, complete.
