### ISSUE TITLE
UI Idea: Error Handling presents error on app

### ISSUE THREAD

**Issue by SadieDragon** [SadieDragon/TPR-Hints-Tool#97]
### Overview
Rather than having it spit out to console, have it spit an error to the app so they can copy paste it more easily. This should make it more obvious to end users when something goes wrong, because sometimes it silently breaks.

### Tasks to Complete
- [ ] Woo, robust error writing (write down all the errors I can think of occurring?)
- [ ] have it clear the tracker completely. all tabs. all of them. Like, the notebook, gone.
- [ ] Create a label with the text for the error
- [ ] Create a button which copies the error to the clipboard
- [ ] Create a button to close the app entirely

### Further Information
There's a copy paste function in lines 57-62 of hints/tabs/spoiler_log.py (which was where the idea came from)
